name: 纯内核编译测试（无补丁）

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: 环境变量配置
        run: |
          sed -i 's/\r$//' config.env
          cat config.env | grep KERNEL_SOURCE= >> $GITHUB_ENV
          cat config.env | grep KERNEL_SOURCE_BRANCH= >> $GITHUB_ENV
          cat config.env | grep KERNEL_CONFIG= >> $GITHUB_ENV
          cat config.env | grep KERNEL_ZIP_NAME= >> $GITHUB_ENV
          cat config.env | grep KERNEL_IMAGE_NAME= >> $GITHUB_ENV

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo -E apt-get -y -qq install git make bc bison ccache openssl zip kmod cpio flex libelf-dev curl libssl-dev libtfm-dev wget device-tree-compiler libyaml-dev ca-certificates python3 binutils binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi

      - name: 下载AOSP clang r596125 (clang 22)
        run: |
          mkdir clang
          wget -q https://commondatastorage.googleapis.com/android-kernel/prebuilts/clang/linux-x86/clang-r596125.tar.gz
          tar -C clang/ -zxf clang-r596125.tar.gz

      - name: 下载内核源码
        run: |
          git clone ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} android-kernel --depth=1

      - name: 编译内核
        run: |
          cd android-kernel
          export PATH=$GITHUB_WORKSPACE/clang/clang-r596125/bin:$PATH
          export KBUILD_BUILD_HOST=test
          export KBUILD_BUILD_USER=test
          make -s -j$(nproc --all) O=out ARCH=arm64 ${{ env.KERNEL_CONFIG }}
          make -j$(nproc --all) CONFIG_DEBUG_SECTION_MISMATCH=y CC="ccache clang" CXX=clang++ O=out ARCH=arm64 CLANG_TRIPLE="aarch64-linux-gnu-" CROSS_COMPILE="aarch64-linux-gnu-" CROSS_COMPILE_ARM32="arm-linux-gnueabi-" LLVM=1 LLVM_IAS=1

      - name: 打包AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3
          sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
          sed -i 's!BLOCK=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!BLOCK=auto;!g' AnyKernel3/anykernel.sh
          sed -i 's/IS_SLOT_DEVICE=0;/IS_SLOT_DEVICE=auto;/g' AnyKernel3/anykernel.sh
          cp android-kernel/out/arch/arm64/boot/${{ env.KERNEL_IMAGE_NAME }} AnyKernel3/
          rm -rf AnyKernel3/.git* AnyKernel3/README.md
          rm -rf AnyKernel3/ramdisk AnyKernel3/modules AnyKernel3/patch

      - name: 上传产物
        uses: actions/upload-artifact@v4
        with:
          name: pure-kernel-test
          path: AnyKernel3/*
